CFLAGS+= -DSQLITE_OS_OTHER=1
CFLAGS+= -DSQLITE_COS_PROFILE_VFS=1
CFLAGS+= -DDSQLITE_COS_PROFILE_MUTEX=1
CFLAGS+= -DSQLITE_COS_PROFILE_MEMORY=0

SRC=$(wildcard *.c)
HDR=$(wildcard *.h)
EXE=sqlite

all:
	$(CC) $(CFLAGS) -o $(EXE) $(SRC)

clean:
	rm -f $(EXE)